server:
  port: 8085
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/college
    username: root
    password: 1212
  jpa:
    hibernate:
      ddl-auto: update
      database-platform: org.hibernate.dialect.MySqlDialect
      database: MYSQL
      show-sql: true
      format-sql: true
      properties:
        hibernate:
          use-new-id-generator-mappings: true
          dialect: org.hibernate.dialect.MySqlDialect